### ISSUE TITLE
JARs in Maven are empty

### ISSUE THREAD

**Issue by btwilk** [JetBrains/lincheck#190]
https://mvnrepository.com/artifact/org.jetbrains.kotlinx/lincheck

The Central repository has JAR artifacts for v2.17, v2.18, and v2.18.1 but they are all essentially empty (no class files).

**Comment by btwilk** [comment]
Ah I just saw that there is a separate artifact lincheck-jvm with the class files. Can someone help me understand why there are two artifacts?

**Comment by alefedor** [comment]
Hi @btwilk ,

We have "*-jvm" versions because we build Lincheck as a [multiplatform](https://kotlinlang.org/docs/multiplatform.html) project.

In a gradle project, both `lincheck` and `lincheck-jvm` are essentially the same and both 
```
testImplementation("org.jetbrains.kotlinx:lincheck-jvm:2.18.1")
```
and 
```
testImplementation("org.jetbrains.kotlinx:lincheck:2.18.1")
```
work.

As far as I remember, in a maven project, only `lincheck-jvm` can be used; that is probably a reason to explicitly publish the jvm version.

So, to answer your question, this duplication is an artifact of multiplatform publishing. For example, Kotlin coroutines library also publishes both [`kotlinx-coroutines-core`](https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core) and [`kotlinx-coroutines-core-jvm`](https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm)
